version: '3.7'

networks:
  proxy:
    external: true
  internal:
    driver: bridge

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - TZ=$TZ
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik:
    container_name: traefik
    image: traefik
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      - TZ=$TZ
    networks:
      - internal
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/rules:/rules
      - ./traefik/traefik.yml:/traefik.yml
      - $SHARED:/shared
      - $CONFIG_PATH/traefik/traefik.log:/traefik.log
    labels:
      - com.centurylinklabs.watchtower.enable=false
      - traefik.enable=true
      # HTTP-to-HTTPS
      - traefik.http.routers.http-catchall.entrypoints=http
      - traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      # HTTP Routers
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.rule=Host(`traefik.$DOMAINNAME`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.domains[0].main=$DOMAINNAME
      - traefik.http.routers.traefik.tls.domains[0].sans=*.$DOMAINNAME
      ## Services - API
      - traefik.http.routers.traefik.service=api@internal
      ## Middlewares
#      - traefik.http.middlewares.auth.forwardauth.address=http://viens.ml/api/?v2/auth&group=1
#      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.middlewares.secure-headers-frame-options.headers.customFrameOptionsValue="allow-from https:$DOMAINNAME"
      - traefik.http.middlewares.chain-all.chain.middlewares=chain-auth@file,secure-headers-frame-options
      - traefik.http.routers.traefik.middlewares=chain-all

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    restart: unless-stopped
    depends_on:
      - traefik
      - keycloak-db
    environment:
      - TZ=$TZ
      - DB_VENDOR=mysql
      - DB_DATABASE=keycloak
      - DB_ADDR=keycloak-db
      - DB_USER=keycloak
      - DB_PASSWORD=$KEYCLOAK_PWD_DB
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=$KEYCLOAK_PWD
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_HOSTNAME=kc.$DOMAINNAME
    networks:
      - internal
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak.entrypoints=https
      - traefik.http.routers.keycloak.rule=Host(`kc.$DOMAINNAME`)
      - traefik.http.routers.keycloak.tls=true
      - traefik.http.services.keycloak.loadbalancer.server.port=8080

  keycloak-db:
    container_name: keycloak-db
    image: mysql
    restart: unless-stopped
    command: --default-time-zone=Europe/Riga
    environment:
      - TZ=$TZ
      - MYSQL_ROOT_PASSWORD=$KEYCLOAK_PWD_DB_ROOT
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=$KEYCLOAK_PWD_DB
    networks:
      - internal
    volumes:
      - $CONFIG_PATH/keycloak/database:/var/lib/mysql

  organizr:
    container_name: organizr
    image: organizrtools/organizr-v2
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - TZ=$TZ
    networks:
      - internal
      - proxy
    ports:
    - 8085:8085
    volumes:
      - $CONFIG_PATH/organizr/config:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.organizr.entrypoints=https
      - traefik.http.routers.organizr.rule=Host(`$DOMAINNAME`,`www.$DOMAINNAME`)
      - traefik.http.routers.organizr.tls=true
      - traefik.http.routers.organizr.middlewares=chain-all

  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    restart: unless-stopped
    depends_on:
      - traefik
      - organizr
    environment:
      - TZ=$TZ
    networks:
      - internal
      - proxy
    volumes:
      - $CONFIG_PATH/jellyfin/config:/config
      - $CONFIG_PATH/jellyfin/cache:/cache
      - $MEDIA:/media
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=https
      - traefik.http.routers.jellyfin.rule=Host(`jf.$DOMAINNAME`)
      - traefik.http.routers.jellyfin.tls=true
#      - traefik.http.routers.jellyfin.middlewares=auth
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

  qbittorent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - TZ=$TZ
    networks:
      - internal
      - proxy
    volumes:
      - $CONFIG_PATH/qbittorrent/config:/config
      - $DOWNLOADS:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
    labels:
      - traefik.enable=true
      - traefik.http.routers.torrent.entrypoints=https
      - traefik.http.routers.torrent.rule=Host(`qb.$DOMAINNAME`)
      - traefik.http.routers.torrent.tls=true
#      - traefik.http.routers.torrent.middlewares=auth
      - traefik.http.services.torrent.loadbalancer.server.port=8080

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - TZ=$TZ
    networks:
      - internal
      - proxy
    volumes:
      - $CONFIG_PATH/jackett/config:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.jackett.entrypoints=https
      - traefik.http.routers.jackett.rule=Host(`jk.$DOMAINNAME`)
      - traefik.http.routers.jackett.tls=true
