entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  traefik:
    address: ":8080"
  dnsovertls:
    address: ":853"
  dns:
    address: ":53"
  udpdns:
    address: ":53/udp"

api:
  dashboard: true

log:
  level: ERROR

accessLog:
  filePath: "/traefik.log"
  bufferingSize: 100

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: "/rules"
    watch: true
