entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  traefik:
    address: ":8080"

api:
  dashboard: true

log:
  level: DEBUG

accessLog:
  filePath: "/traefik.log"
  bufferingSize: 100

providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/rules"
    watch: true
